name: Java CI pipeline
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven 
    - name: Build with Maven
      working-directory: ./Facturacion
      run: mvn clean package
    - name: Upload Artifact 
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: facturacion-war
        path: "/home/runner/work/ProyectoISO815/ProyectoISO815/Facturacion/target/Facturacion-1.0-SNAPSHOT.war"
        if-no-files-found: error