name: Java CI pipeline
on:
  push:
    branches: [ "main" ]

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven 
        
    - run: mvn clean package -DskipTests
    - run: mkdir staging && cp target/Facturacion.jar staging
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
        retention-days: 1
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts
    - name: Deploy to EC2
      run: |
            scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no /home/runner/work/ProyectoISO815/ProyectoISO815/staging/Facturacion.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/opt/app/Facturacion
    - name: Restart app
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          ps -ef | grep "Facturacion" | awk '{print $2}' | xargs kill
          sudo nohup sudo java -jar /var/app/Facturacion/Facturacion.jar